language: python
python:
- 2.6
- 2.7
services:
- redis-server
before_install:
- sudo apt-get update -qq
- sudo apt-get install -qq zookeeper zookeeperd
install:
- pip install -e .[tests]
- pip install coveralls
script:
- py.test test/ --cov=rump --cov-report term-missing
after_success:
- coveralls
deploy:
  provider: pypi
  user: somepie
  password:
    secure: aJWYyjFmdvXDJtNWLDIrd7I7rbSnJBc7NJfgcBMb/nlap9Zzad2J99Vcc9Cs18hVPOpSxx0S4iOWMjAI73CD4Yq3QEAD5wjY9Zae6uqerJQ294Xl8ukOZO9fBCErNnOaNMKLcKLzIqoyOwaueVnrnPdeHns6CpH/LLFU2lHndq4=
  on:
    all_branches: true
    tags: true
